---
- name: Install Mondoo RPM repository
  yum_repository:
    name: mondoo
    description: Mondoo Repository
    baseurl: "{{ mondoo_rpm_repo }}"
    enabled: yes
    gpgcheck: yes
    gpgkey: "{{ mondoo_rpm_gpgkey }}"
  become: true
  when: not ansible_check_mode

- name: Ensure Mondoo agent is installed
  yum:
    name: mondoo
    update_cache: yes
    state: latest
  become: true
  when: not ansible_check_mode
