name: "Build Mondoo Package (Testing)"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version that should be released'
        required: true
        default: '1.2.3'

jobs:
  build-mondoo-payloads:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.inputs.version }}
    steps:
      - uses: actions/checkout@v3

      - name: Create destination folder
        run: |
          cd helper/
          mkdir dist
          cp mondoo.sh dist/ 
          cp mondoo.ps1 dist/

      - name: Tar up mondoo.sh
        run: |
          cd helper/
          cp mondoo.sh mondoo
          tar czf dist/mondoo_${VERSION}_linux_noarch.tar.gz ./mondoo
          rm mondoo

      - name: Zip up mondoo.ps1
        run: |
          cd helper/
          zip dist/mondoo_${VERSION}_windows_noarch.zip mondoo.ps1

      - name: Install RPM tools
        run: |
          sudo apt update && sudo apt install -y rpm gpg

      - name: Build RPM
        run: |
          cd helper/
          ./build-rpms.sh ${VERSION} ./dist

      - name: Authenticate with GCloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Setup GCloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Download Signing Keys
        env:
          KEY_PATH: ${{ runner.temp }}
        run: |
          gcloud --project=mondoo-base-infra secrets versions access latest --secret=gpg-package-signing-cert-public-2023 --out-file=${KEY_PATH}/public.gpg
          gpg --import ${KEY_PATH}/public.gpg
          gcloud --project=mondoo-base-infra secrets versions access latest --secret=gpg-package-signing-cert-private-2023 --out-file=${KEY_PATH}/private.gpg
          gpg --import --allow-secret-key-import ${KEY_PATH}/private.gpg

      - name: Check GPG Keys
        run: |
          gpg --list-keys
          gpg --list-secret-keys

      - name: Sign RPMs
        run: |
          cd helper/
          rpmsign --define='%_gpg_name Mondoo Inc' --addsign ./dist/*rpm

      - name: Build DEBs
        run: |
          cd helper/
          ./build-deb.sh ${VERSION} ./dist

      - name: Generate Checksums
        run: |
          cd helper/dist
          sha256sum *linux* > checksums.linux.txt
          cd -

      - name: Upload files to releases.mondoo.com
        run: |
          gsutil cp helper/dist/mondoo.sh                          gs://releases-us.mondoo.io/mondoo/${VERSION}/mondoo.sh
          gsutil cp helper/dist/mondoo.ps1                         gs://releases-us.mondoo.io/mondoo/${VERSION}/mondoo.ps1
          gsutil cp helper/dist/mondoo_${VERSION}_windows_noarch.zip      gs://releases-us.mondoo.io/mondoo/${VERSION}/mondoo_${VERSION}_windows_noarch.zip
          gsutil cp helper/dist/mondoo_${VERSION}_linux_noarch.tar.gz     gs://releases-us.mondoo.io/mondoo/${VERSION}/mondoo_${VERSION}_linux_noarch.tar.gz
          gsutil cp helper/dist/mondoo_${VERSION}_linux_noarch.rpm gs://releases-us.mondoo.io/mondoo/${VERSION}/mondoo_${VERSION}_linux_noarch.rpm
          gsutil cp helper/dist/mondoo_${VERSION}_linux_noarch.deb gs://releases-us.mondoo.io/mondoo/${VERSION}/mondoo_${VERSION}_linux_noarch.deb
          gsutil cp helper/dist/checksums.linux.txt                gs://releases-us.mondoo.io/mondoo/${VERSION}/checksums.linux.txt

      - name: Upload files to Github Release Page
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          files: |
            helper/dist/mondoo.sh
            helper/dist/mondoo.ps1
            helper/dist/mondoo_${{ github.event.inputs.version }}_windows_noarch.zip
            helper/dist/mondoo_${{ github.event.inputs.version }}_linux_noarch.tar.gz
            helper/dist/mondoo_${{ github.event.inputs.version }}_linux_noarch.rpm
            helper/dist/mondoo_${{ github.event.inputs.version }}_linux_noarch.deb
            
      - name: Create Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mondoo-${{ github.event.inputs.version }}
          path: helper/dist
          retention-days: 7