name: "Build Mondoo Package (Testing)"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version that should be released'
        required: true
        default: '1.2.3'

jobs:
  build-mondoo-payloads:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.inputs.version }}
    steps:
      - uses: actions/checkout@v3

      - name: Create destination folder
        run: |
          mkdir dist
          cp mondoo.sh dist/ 
          cp mondoo.ps1 dist/

      - name: Tar up mondoo.sh
        run: |
          cp mondoo.sh mondoo
          tar czf dist/mondoo_${VERSION}_linux.tar.gz ./mondoo
          rm mondoo

      - name: Zip up mondoo.ps1
        run: |
          zip dist/mondoo_${VERSION}_windows.zip mondoo.ps1

      - name: Install RPM tools
        run: |
          sudo apt update && sudo apt install -y rpm gpg

      - name: Build RPM
        run: |
          ./build-rpms.sh ${VERSION} ./dist

      - name: Authenticate with GCloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Setup GCloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: download signing keys
        env:
          KEY_PATH: ${{ runner.temp }}
        run: |
          gcloud --project=mondoo-base-infra secrets versions access latest --secret=gpg-package-signing-cert-public-2023 --out-file=${KEY_PATH}/public.gpg
          gpg --import ${KEY_PATH}/public.gpg
          gcloud --project=mondoo-base-infra secrets versions access latest --secret=gpg-package-signing-cert-private-2023 --out-file=${KEY_FILE}/private.gpg
          gpg --import --allow-secret-key-import ${KEY_PATH}/private.gpg

      - name: Check GPG Keys
        run: |
          gpg --list-keys
          gpg --list-secret-keys

      - name: Sign RPMs
        run: |
          rpmsign --define='%_gpg_name Hello Mondoo' --addsign ./dist/*rpm

      - name: Build DEBs
        run: |
          ./build-deb.sh ${VERSION} ./dist

      - name: Generate Checksums
        run: |
          cd dist
          sha256sum *linux* > checksums.linux.txt
          cd -

      - name: Upload files to releases.mondoo.com
        run: |
          gsutil cp dist/mondoo_${VERSION}_windows.zip gs://releases-us.mondoo.io/mondoo/${VERSION}/mondoo_${VERSION}_windows.zip
          gsutil cp dist/mondoo_${VERSION}_linux.tar.gz gs://releases-us.mondoo.io/mondoo/${VERSION}/mondoo_${VERSION}_linux.tar.gz
          gsutil cp dist/mondoo_${VERSION}_linux_noarch.rpm gs://releases-us.mondoo.io/mondoo/${VERSTION}/mondoo_${VERSION}_linux_noarch.rpm
          gsutil cp dist/mondoo_${VERSION}_linux_noarch.deb gs://releases-us.mondoo.io/mondoo/${VERSION}/mondoo_${VERSION}_linux_noarch.deb
          gsutil cp dist/checksums.linux.txt gs://releases-us.mondoo.io/mondoo/${VERSION}/checksums.linux.txt

      - name: Upload files to Github Release Page
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/mondoo_${VERSION}_windows.zip
            dist/mondoo_${VERSION}_linux.tar.gz
            dist/mondoo_${VERSION}_linux_noarch.rpm
            dist/mondoo_${VERSION}_linux_noarch.deb
            
      - name: Create Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mondoo-${{ github.event.inputs.version }}
          path: dist
          retention-days: 7